### ISSUE TITLE
The connect modal get stuck on `Select wallets` step

### ISSUE THREAD

**Issue by rychnovsky** [Crossmint/connect#20]
Hello, 
we are experiencing a new issue regarding the Crossmint connect button. 
version: 0.0.9-alpha.6

1. The user clicks on Connect button, and a Crossmint window is opened correctly
2. The user sees all the permissions he will give to the app, and clicks on "Connect" button
3. A "Select wallets access" window appears for a second and is closed immediately, the user has no chance to select any wallet. At this moment, the user is stuck. They can click on the "Connect" button again with the same result, so it is impossible to get past this step. 

You can even experience the same behavior on the official demo: https://embed-crossmint.vercel.app/

Notes:
It worked fine a week ago with the same version and configuration on the client-side. 
If the user has already authorized the app, step 2 is skipped and the process works fine.

**Comment by dmulvi** [comment]
@rychnovsky - thanks for the report! This issue is fixed. It doesn't require a package update.
